market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import shopcart, addcart, pay
from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword

urlpatterns = [
    url(r'^shopcart/$', shopcart, name='shopcart'),  # 购物车
    url(r'^addcart/$', addcart, name='addcart'),  #添加购物车
    url(r'^pay/$', pay, name='pay'),  #支付成功
]

market/apps/goods/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from goods.views import index, detail, category, city, village, village_edit

urlpatterns = [
    # 设置缓存
    url(r'^$', cache_page(3600)(index), name='index'),
    url(r'^(?P<id>\d+).html$', detail, name='detail'),
    url(r'^category/(?P<cate_id>\d+)/(?P<order_id>\d)/$', category, name='category'),
    url(r'^city/$', city, name='city'),
    url(r'^village/$', village, name='village'),
    url(r'^village_edit/(?P<id>\d+)/$', village_edit, name='village_edit'),

]

market/apps/order/urls.py
from django.conf.urls import url

from order.views import tureorder, address, add, edit, addedit, delete, default, order,addorder
from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword

urlpatterns = [
    url(r'^tureorder/$', tureorder, name='tureorder'),  # 确认订单
    url(r'^order/$', order, name='order'),  # 确认订单
    url(r'^address/$', address, name='address'),  # 地址
    url(r'^addedit/$', addedit, name='addedit'),  # 地址
    url(r'^add/$', add, name='add'),  # 添加地址
    url(r'^edit/(?P<id>\d+)/$', edit, name='edit'),  # 修改地址
    url(r'^delete/$', delete, name='delete'),  # 删除地址
    url(r'^default/$', default, name='default'),  # 设置为默认值地址
    url(r'^addorder/$', addorder, name='addorder'),  # 设置为默认值地址
]

market/apps/person/urls.py
from django.conf.urls import url

from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword, send_phone_code

urlpatterns = [
    url(r'^login/$', login, name='login'),  # 登录
    url(r'^reg/$', myregister, name='register'),  # 注册
    url(r'^member/$', member, name='member'),  # 个人中心
    url(r'^allorder/$', allorder, name='allorder'),  # 订单
    url(r'^gladdress/$', gladdress, name='gladdress'),  # 地址
    url(r'^info/$', info, name='info'),  # 个人资料
    url(r'^forget/$', forgetpassword, name='forget'),  # 忘记密码
    url(r'^send/$', send_phone_code, name='send'),  # 验证码
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    url(r'^person/', include('person.urls', namespace='person')),
    url(r'^index/', include('goods.urls', namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
]

market/apps/cart/models.py
from django.db import models

# Create your models here.

market/apps/order/models.py
from django.db import models

from db.commonmodel import Basemodels


class Paymethod(Basemodels):
    pay_name = models.CharField(verbose_name='支付方式', max_length=20)
    logo = models.ImageField(upload_to='pay/', verbose_name='logo')

    class Meta:
        db_table = 'paymethod'
        verbose_name = "支付方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.pay_name


class Transport(Basemodels):
    name = models.CharField(verbose_name='配送方式', max_length=20)
    money = models.DecimalField(verbose_name='金额', max_digits=9, decimal_places=2, default=0)

    class Meta:
        db_table = 'transport'
        verbose_name = "配送方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Order_info(Basemodels):
    choices = [
        (0, '待付款'),
        (1, '退发货'),
        (2, '待收货'),
        (3, '待评价'),
        (4, '已完成'),
    ]
    ordernum = models.CharField(max_length=255, verbose_name='订单编号', default=0)
    user = models.ForeignKey(to="person.register", verbose_name='用户id')
    name = models.CharField(max_length=30, verbose_name='收货人姓名')
    tel = models.CharField(max_length=11, verbose_name='收货人电话')
    address = models.CharField(max_length=200, verbose_name='地址信息')
    order_status = models.SmallIntegerField(choices=choices, default=0, verbose_name='订单状态')
    transport = models.CharField(max_length=30, verbose_name='运输方式')
    trans_money = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='运输金额')
    paymethod = models.ForeignKey(to='Paymethod', verbose_name='支付方式id', null=True, blank=True)
    order_money = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='订单商品金额', default=0)
    total = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='订单总金额', default=0)
    real_money = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='实付金额')
    comment = models.CharField(max_length=255, verbose_name='备注', null=True, blank=True)

    class Meta:
        db_table = 'order_info'
        verbose_name = '订单信息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ordernum


class Order_goods(Basemodels):
    order = models.ForeignKey(to='Order_info', verbose_name='订单id')
    sku = models.ForeignKey(to='goods.SKU', verbose_name='商品sku_id')
    number = models.IntegerField(verbose_name='商品数量')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='商品价格')

    class Meta:
        db_table = 'order_goods'
        verbose_name = '订单商品表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku

market/apps/order/forms.py
from django import forms

from person.models import Address


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['add_time', 'update_time', 'isdelete', 'log']

        error_messages = {
            'name': {
                'required': "请填写用户名！",
            },
            'tel': {
                'required': "请填写手机号码！",
            },
            'brief': {
                'required': "请填写详细地址！",
            },
            'hcity': {
                'required': "请填写完整地址！",
            },
            'hproper': {
                'required': "请填写完整地址！",
            },
            'harea': {
                'required': "请填写完整地址！",
            },
        }

    def clean(self):
        user_id = self.data.get('id')
        count = Address.objects.filter(log_id=user_id, isdelete=False).count()
        if count >= 6:
            raise forms.ValidationError('地址不能超过6个')

        isDefault = self.cleaned_data.get('isDefault')
        if isDefault:
            Address.objects.filter(log_id=user_id).update(isDefault=False)
        return self.cleaned_data


class AddresseditForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['add_time', 'update_time', 'isdelete', 'log']

        error_messages = {
            'name': {
                'required': "请填写用户名！",
            },
            'tel': {
                'required': "请填写手机号码！",
            },
            'brief': {
                'required': "请填写详细地址！",
            },
            'hcity': {
                'required': "请填写完整地址！",
            },
            'hproper': {
                'required': "请填写完整地址！",
            },
            'harea': {
                'required': "请填写完整地址！",
            },
        }

    def clean(self):
        user_id = self.data.get('id')

        isDefault = self.cleaned_data.get('isDefault')
        if isDefault:
            Address.objects.filter(log_id=user_id).update(isDefault=False)
        return self.cleaned_data

market/apps/cart/views.py
import os
from urllib.parse import urlparse, parse_qs

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django_redis import get_redis_connection

from goods.models import SKU
from market.settings import BASE_DIR
from order.models import Order_info
# from utils.alipay.alipay import AliPay
from alipay import AliPay
import time


def shopcart(request):
    user_id = request.session.get('id')
    if user_id is None:
        return redirect('person:login')
    r = get_redis_connection('default')
    user_key = "user_key_{}".format(user_id)
    cartgoods = r.hgetall(user_key)

    cartlist = []

    sku = request.POST.get("sku_id")
    if sku:
        sku = int(sku)
        # num = r.hget(user_key, sku)
        # num = num.decode('utf-8')
        r.hdel(user_key, sku)
        return JsonResponse({"code": 0})

    for k, v in cartgoods.items():
        sku_id = k.decode('utf-8')
        goods = SKU.objects.get(pk=sku_id)
        goods.num = v.decode('utf-8')
        cartlist.append(goods)

    context = {
        'goods': cartlist,

    }
    return render(request, 'cart/shopcart.html', context)


def addcart(request):
    # 判断用户是否登录
    user_id = request.session.get('id')
    if user_id is None:
        return JsonResponse({"code": 1, "err": "没有登录"})

    # 获取参数
    sku_id = request.POST.get('sku_id')
    num = request.POST.get('num')

    try:
        sku_id = int(sku_id)
        num = int(num)
    except:
        return JsonResponse({"code": 2, "err": "参数错误"})

    # 判断商品是否存在
    try:
        goods = SKU.objects.get(pk=sku_id)
    except:
        return JsonResponse({"code": 4, "err": "商品不存在"})

    # 判断库存
    if goods.stock < num:
        return JsonResponse({"code": 3, "err": "参数错误"})

    # 将数据存入redis中
    r = get_redis_connection('default')
    user_key = "user_key_{}".format(user_id)
    mycart = r.hincrby(user_key, sku_id, num)
    total = 0
    totalcart = r.hvals(user_key)
    for v in totalcart:
        total += int(v)
    if mycart == 0:
        r.hdel(user_key, sku_id)
    return JsonResponse({"code": 0, "total": total})


def pay(request):
    # """支付宝支付成功后通知接口验证"""
    # order_id = request.GET.get("out_trade_no")
    # order = Order_info.objects.get(ordernum=order_id)
    # price = str(order.total)
    # # print(order.ordernum)
    # # 传递参数初始化支付类
    # alipay = AliPay(
    #     appid="2016092400584100",  # 设置签约的appid
    #     app_notify_url="http://127.0.0.1:8000/cart/pay/",  # 异步支付通知url
    #     app_private_key_path=os.path.join(BASE_DIR, 'apps/utils/alipay/ying_yong_si_yao.txt'),  # 设置应用私钥
    #     alipay_public_key_path=os.path.join(BASE_DIR, 'apps/utils/alipay/zhi_fu_bao_gong_yao.txt'),
    #     # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
    #     debug=True,  # 默认False,                                   # 设置是否是沙箱环境，True是沙箱环境
    #     return_url="http://127.0.0.1:8000/cart/pay/"  # 同步支付通知url
    # )
    # # 传递参数执行支付类里的direct_pay方法，返回签名后的支付参数，
    #
    # url = alipay.direct_pay(
    #     subject="测试订单",  # 订单名称
    #     # 订单号生成，一般是当前时间(精确到秒)+用户ID+随机数
    #     out_trade_no=order.ordernum,  # 订单号
    #     total_amount=price,  # 支付金额
    #     return_url="http://127.0.0.1:8000/cart/pay/"  # 支付成功后，跳转url
    # )
    # # 接收支付宝支付成功后，向我们设置的同步支付通知url，请求的参数
    # return_url = "https://openapi.alipaydev.com/gateway.do?{data}".format(data=url)
    #
    # # 将同步支付通知url,传到urlparse
    # o = urlparse(return_url)
    # # 获取到URL的各种参数
    # query = parse_qs(o.query)
    # # 定义一个字典来存放，循环获取到的URL参数
    # processed_query = {}
    # # 将URL参数里的sign字段拿出来
    # ali_sign = query.pop("sign")[0]
    #
    # # 循环出URL里的参数
    # for key, value in query.items():
    #     # 将循环到的参数，以键值对形式追加到processed_query字典
    #     processed_query[key] = value[0]
    # # 将循环组合的参数字典，以及拿出来的sign字段，传进支付类里的verify方法，返回验证合法性，返回布尔值，True为合法，表示支付确实成功了，这就是验证是否是伪造支付成功请求
    # res = alipay.verify(processed_query, ali_sign)
    # print(alipay.verify(processed_query, ali_sign))
    # if res is False:
    #     context = {
    #         "mess": "支付失败"
    #     }
    # else:
    #     context = {
    #         "mess": "支付成功"
    #     }
    #     Order_info.objects.filter(ordernum=order_id).update(order_status=1)
    # # 如果别人伪造支付成功请求，它不知道我们的支付宝公钥，伪造的就无法通过验证，测试可以将支付宝公钥更改一下，在验证就会失败，别忘了改回来
    # return render(request, 'cart/pay.html', context)

    # try:
    #     order = Order_info.objects.get(ordernum=out_trade_no)
    # except Order_info.DoesNotExist:
    #     return redirect('cart:shopcart')

    # print(out_trade_no)

    app_private_key_string = open(os.path.join(BASE_DIR, 'apps/utils/alipay/ying_yong_si_yao.txt')).read()
    alipay_public_key_string = open(os.path.join(BASE_DIR, 'apps/utils/alipay/ying_yong_gong_yao.txt')).read()

    alipay = AliPay(
        appid="2016092400584100",
        app_notify_url=None,  # 默认回调url
        app_private_key_string=app_private_key_string,
        # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2",  # RSA 或者 RSA2
        debug=True  # 默认False
    )
    out_trade_no = request.GET.get("out_trade_no")
    paid = False
    for i in range(3):
        result = alipay.api_alipay_trade_query(out_trade_no=out_trade_no)
        if result.get("trade_status", "") == "TRADE_SUCCESS":
            paid = True
            break
        else:
            time.sleep(3)

    if paid is False:
        context = {
            "mess": "支付失败"
        }
    else:
        context = {
            "mess": "支付成功"
        }
        Order_info.objects.filter(ordernum=out_trade_no, order_status=0).update(order_status=1)
    return render(request, 'cart/pay.html', context)

market/templates/cart/pay.html
{% extends 'public/base.html' %}
{% load static %}
 {% block header %}
    <body style="background: #f0f0f0;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">完成支付</a>
            </h1>
	    </header>
 {% endblock %}
{% block content %}
     <div style="height: 49px;"></div>
	    <ul class="order-detail">
	       <li><span>支付：</span>{{ mess }}</li>

	    </ul>

	    <input type="button" class="login-btn" value="查看订单">
{% endblock %}

market/templates/cart/shopcart.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">购物车</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="shopcart-list">
        {% for good in goods %}
            <li class="cart">
                <label class="am-checkbox am-warning">
                    <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
                </label>
                <a href="{% url 'goods:detail' good.id %}"><img src="{{ MEDIA_URL }}{{ good.img }}"
                                                                class="shop-pic"/></a>
                <div class="shop-list-mid">
                    <div class="tit"><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></div>
                    <b class="shop-list-price">￥<span class='price'>{{ good.price }}</span> </b>
                </div>
                <div class="list-cart1">
                    <div class="d-stock">
                        <a class="decrease">-</a>
                        <input readonly="" sku_id="{{ good.id }}" single_price="{{ good.price }}" class="text_box num" name="" type="text"
                               value="{{ good.num }}">
                        <a class="increase">+</a>
                    </div>
                </div>
            </li>
        {% endfor %}

    </ul>
    <div class="login-logo"  {% if goods %} style="display: none" {% else %} style="display: block"{% endif %}>
        <img src="{% static 'images/care.png' %}">
        <p>亲、您的购物车还是空空的哦，快去装满它!</p>
        <a href="{% url 'goods:index' %}" class="goshopping">前去逛逛</a>
    </div>

    <div class="shop-fix">

        <label class="am-checkbox am-warning">
            <input id="checkall" type="checkbox" checked="checked" value="" data-am-ucheck checked>
        </label>
        <a class="del">全选</a>
        <a href="javascript:;" class="js-btn" id="mycount">去结算</a>
        <div class="js-text">

            <P>合计：<b>￥<span>00.00</span></b></P>
            <p class="js-car">免费配送</p>
        </div>
    </div>
{% endblock %}

{% block foot %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:index' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:shopcart' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'person:allorder' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="member.html" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>


{% endblock %}

{% block foot_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var sku_id = self.siblings('input').attr('sku_id');
                var current_num = parseInt(self.siblings('input').val());
                var num = 1;
                $.ajax({
                    type: "POST",
                    url: "{% url 'cart:addcart' %}",
                    data: {"sku_id": sku_id, "num": num, "csrfmiddlewaretoken": "{{ csrf_token  }}"},
                    dataType: "json",
                    success: function (data) {
                        if (data.code == 0) {
                            current_num += 1;
                            self.siblings('input').val(current_num);
                            totalprice()
                        }
                    }
                });
            });
            $('.decrease').click(function () {
                var self = $(this);
                var sku_id = self.siblings('input').attr('sku_id');
                var current_num = parseInt(self.siblings('input').val());

                var num = -1;
                $.ajax({
                    type: "POST",
                    url: "{% url 'cart:addcart' %}",
                    data: {"sku_id": sku_id, "num": num, "csrfmiddlewaretoken": "{{ csrf_token  }}"},
                    dataType: "json",
                    success: function (data) {
                        if (data.code == 0) {
                            if (current_num > 1) {
                                current_num -= 1;
                                self.siblings('input').val(current_num);
                                totalprice();
                            } else if (current_num == 1) {
                                self.siblings('input').parents("li").remove();
                                if ($(".shopcart-list li").length == 0) {
                                    $('.login-logo').show()
                                }
                            }
                        }
                    }
                });


            });

            function totalprice() {
                var checked_li = $('.shopcart-list li').find(':checked');
                {#console.debug(checked_li)#}
                var total = 0;
                $.each(checked_li, function (i, e) {
                    var price = $(e).parents('li').find('.price').text();
                    var num = $(e).parents('li').find('.text_box').val();
                    total += price * num;
                });
                {#console.debug(total)#}
                $('.js-text').find('span').text(total.toFixed(2))

            }

            totalprice();

            // 全选框
            $("#checkall").on("change", function () {
                var status = $(this).prop("checked");
                {#console.debug(status)#}
                $('.shopcart-list').find(':checkbox').prop('checked', status);
                totalprice();
            });

            //复选框
            $('.shopcart-list').find(':checkbox').on('change', function () {
                if ($('.shopcart-list').find(':checkbox').length == $('.shopcart-list').find(':checked').length) {
                    $("#checkall").prop("checked", true);
                    totalprice();
                } else {
                    $("#checkall").prop("checked", false);
                    totalprice();
                }
            })


            //结算
            $('#mycount').on('click', function () {
                //商品id , 数量 ,总价
                var li = $('.shopcart-list').find(':checked').parents('li');
                var num = li.find('.num');
                var goods ="";
                {#var single_price =[];#}
                $.each(num, function (i, e) {
                    goods += $(e).attr('sku_id');
                    goods +=" ";
                });
                console.debug(goods);
                $.ajax({
                    type:"POST",
                    url:"{% url 'order:addorder' %}",
                    data:{"goods":goods,"csrfmiddlewaretoken":"{{ csrf_token }}"},
                    dataType:"json",
                    success:function (data) {
                        if(data.code==0){
                             location.href="{% url 'order:tureorder' %}"
                        }
                    }
                })
            })
        })
    </script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>
{% endblock %}
 

market/templates/cart/tureorder.html
{% extends 'public/base.html' %}
{% load static %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">确认订单</a>
        </h1>
    </header>
{% endblock %}

{% block content %}
    <div style="height: 49px;"></div>
    <form action="" method="post">
        {% csrf_token %}
        {% if address %}
            <input type="hidden" name="address" value="{{ address.pk }}">
            <h5 class="order-tit">默认收货地址</h5>
            <div class="order-name">
                <a href="{% url "person:gladdress" %}">
                    <p class="order-tele"
                       style="font-size: 1.6rem">{{ address.name }}&nbsp;&nbsp;&nbsp;{{ address.tel }}</p>
                    <p class="order-add" style="font-size: 1.6rem">
                        {{ address.hcity }}{{ address.hproper }}-{{ address.harea }}{{ address.brief }}</p>
                </a>
                <i class="am-icon-angle-right"></i>
            </div>
        {% else %}
            <div class="add-address">
                <a href="{% url 'order:address' %}">+新建收货地址</a>
                <i class="am-icon-angle-right"></i>
            </div>
        {% endif %}



        <div style="background: #eee; height: 10px;"></div>
        <ul class="shopcart-list" style="padding-bottom: 0;">
            {% for goods in goodslist %}
                <li>
                    <input type="hidden" name="sku_id" value="{{ goods.pk }}">
                    <img src="{{ MEDIA_URL }}{{ goods.img }}" class="shop-pic"/>
                    <div class="order-mid">
                        <div class="tit">{{ goods.name }}</div>
                        <div class="order-price">￥<span class="price">{{ goods.price }}</span> <i>X<span
                                class="num">{{ goods.num }}</span></i></div>
                    </div>
                </li>
            {% endfor %}

        </ul>
        <ul class="order-infor">
            <li class="order-infor-first">
                <span>商品总计：</span>
                <i>￥<span id="total"></span></i>
            </li>
            <li class="order-infor-first">
                <span>运输方式：</span>

                <i>
                    <select name="transport" id="">
                        {% for t in transport %}
                            <option name="{{ t.id }}" value="{{ t.id }}" transmoney="{{ t.money }}">{{ t.name }} --￥{{ t.money }}</option>
                        {% endfor %}
                    </select>
                </i>
            </li>
        </ul>

    <div style="background: #eee; height: 10px;"></div>
    <textarea placeholder="备注说明" name="comment" class="bz-infor"></textarea>
     </form>
    <div style="background: #eee; height: 10px;"></div>
    <div style="height: 55px;"></div>
    <div class="shop-fix">
        <div class="order-text">
            应付总额：<span>￥<span id="myprice"></span></span>
        </div>
        <a href="javascript:;" class="js-btn">提交订单</a>
    </div>
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:index' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:shopcart' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'person:allorder' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'person:member' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block foot_js %}
    <script>
        $(function () {
            // 计算价格
            function totalprice() {
                var li = $(".shopcart-list li");
                var price = 0;
                $.each(li, function (i, e) {
                    var single_price = $(e).find(".price").text();
                    var number = $(e).find(".num").text();
                    price += single_price * number
                });

                $('.order-infor').find("#total").text(price.toFixed(2));
                var transmoney = $('.order-infor-first').find(":selected").attr('transmoney');
                myprice = parseFloat(price) + parseFloat(transmoney);
                $('.order-text').find("#myprice").text(myprice.toFixed(2));
            }

            totalprice();

            $('.order-infor-first').find("select").on("change", function () {
                totalprice();
            });

            $(".js-btn").on("click", function () {
                var data = $('form').serialize();
                $.ajax({
                    type:"post",
                    url:"",
                    data:data,
                    dataType:"json",
                    success:function (data) {
                        if(data.code==0){
                           location.href="{% url 'order:order' %}?ordernum="+data.ordernum
                        }else{
                            alert('订单生成失败')
                        }
                    }
                })
            })
        })

    </script>
{% endblock %}