market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import shopcart, addcart, pay
from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword

urlpatterns = [
    url(r'^shopcart/$', shopcart, name='shopcart'),  # 购物车
    url(r'^addcart/$', addcart, name='addcart'),  #添加购物车
    url(r'^pay/$', pay, name='pay'),  #支付成功
]

market/apps/goods/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from goods.views import index, detail, category, city, village, village_edit

urlpatterns = [
    # 设置缓存
    url(r'^$', cache_page(3600)(index), name='index'),
    url(r'^(?P<id>\d+).html$', detail, name='detail'),
    url(r'^category/(?P<cate_id>\d+)/(?P<order_id>\d)/$', category, name='category'),
    url(r'^city/$', city, name='city'),
    url(r'^village/$', village, name='village'),
    url(r'^village_edit/(?P<id>\d+)/$', village_edit, name='village_edit'),

]

market/apps/order/urls.py
from django.conf.urls import url

from order.views import tureorder, address, add, edit, addedit, delete, default, order,addorder
from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword

urlpatterns = [
    url(r'^tureorder/$', tureorder, name='tureorder'),  # 确认订单
    url(r'^order/$', order, name='order'),  # 确认订单
    url(r'^address/$', address, name='address'),  # 地址
    url(r'^addedit/$', addedit, name='addedit'),  # 地址
    url(r'^add/$', add, name='add'),  # 添加地址
    url(r'^edit/(?P<id>\d+)/$', edit, name='edit'),  # 修改地址
    url(r'^delete/$', delete, name='delete'),  # 删除地址
    url(r'^default/$', default, name='default'),  # 设置为默认值地址
    url(r'^addorder/$', addorder, name='addorder'),  # 设置为默认值地址
]

market/apps/person/urls.py
from django.conf.urls import url

from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword, send_phone_code

urlpatterns = [
    url(r'^login/$', login, name='login'),  # 登录
    url(r'^reg/$', myregister, name='register'),  # 注册
    url(r'^member/$', member, name='member'),  # 个人中心
    url(r'^allorder/$', allorder, name='allorder'),  # 订单
    url(r'^gladdress/$', gladdress, name='gladdress'),  # 地址
    url(r'^info/$', info, name='info'),  # 个人资料
    url(r'^forget/$', forgetpassword, name='forget'),  # 忘记密码
    url(r'^send/$', send_phone_code, name='send'),  # 验证码
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    url(r'^person/', include('person.urls', namespace='person')),
    url(r'^index/', include('goods.urls', namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
]

market/apps/person/models.py
from django.core.validators import RegexValidator
from django.db import models

# 登录注册表
from db.commonmodel import Basemodels


class register(models.Model):
    tel = models.CharField(max_length=11)
    password = models.CharField(max_length=20)
    check = models.CharField(max_length=10, default=0)
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'register'

    def __str__(self):
        return self.tel


# 个人信息表
class User_info(models.Model):
    choice = [(1, '男'),
              (2, '女')]
    log_id = models.OneToOneField(to='register')
    head_sculpture = models.CharField(max_length=100, default=0)
    head_img = models.ImageField(upload_to='', default='images/infortx.png', verbose_name='头像')
    nickname = models.CharField(max_length=30)
    sex = models.SmallIntegerField(choices=choice)
    birthday = models.DateField()
    school = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    hometown = models.CharField(max_length=200)
    tel = models.CharField(max_length=11)
    add_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    isdelete = models.SmallIntegerField(default=0)

    class Meta:
        db_table = 'user_info'

    def __str__(self):
        return self.nickname


# 收货地址表
class Address(Basemodels):
    log = models.ForeignKey(to='register', verbose_name='用户标识')
    name = models.CharField(max_length=30, verbose_name='用户姓名')
    tel = models.CharField(max_length=11, verbose_name='用户号码',
                           validators=[RegexValidator(r'^1[3-9]\d{9}$', '手机号码格式错误')])
    hcity = models.CharField(max_length=100, verbose_name="省")
    hproper = models.CharField(max_length=100, blank=True, default='', verbose_name="市")
    harea = models.CharField(max_length=100, blank=True, default='', verbose_name="区")
    brief = models.CharField(max_length=255, verbose_name="详细地址")
    isDefault = models.BooleanField(default=False, blank=True, verbose_name="是否设置为默认", null=False)

    class Meta:
        db_table = 'address'
        verbose_name = "收货地址"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

market/apps/person/forms.py
import hashlib

from django import forms
from django.core import validators

# 注册验证
from django_redis import get_redis_connection

from person.helper import set_password
from person.models import register


class MyregisterFrom(forms.Form):
    tel = forms.CharField(validators=[validators.RegexValidator(r'1[3456789]\d{9}', message='手机号格式不正确')],
                          error_messages={'required': '手机号必须填写'})
    password = forms.CharField(max_length=20, min_length=6,
                               error_messages={'required': '密码必须填写', 'max_length': '密码不能大于20位',
                                               'min_length': '密码不能少于6位'})
    repassword = forms.CharField(max_length=20, min_length=6,
                                 error_messages={'required': '密码必须填写', 'max_length': '密码不能大于20位',
                                                 'min_length': '密码不能少于6位'})

    code = forms.CharField(error_messages={'required': '验证码必须填写'})

    # 验证两次输入的密码是否一致
    def clean(self):
        data = self.cleaned_data
        if data.get('password') and data.get('repassword') and data.get('password') != data.get('repassword'):
            raise forms.ValidationError({'repassword': '两次密码不一致'})
        return data

    # 验证手机号是否已经被注册过
    def clean_tel(self):
        data = self.cleaned_data
        tel = data.get('tel')
        rs = register.objects.filter(tel=tel).exists()
        if rs:
            raise forms.ValidationError("手机号码已经被注册")
        return tel

    # 验证验证码是否正确
    def clean_code(self):
        tel = self.cleaned_data.get("tel")
        code = self.cleaned_data.get('code')
        # 获取redis中的
        r = get_redis_connection("default")
        if tel:
            # 获取 redis中获取的值 是二进制编码,必须解码
            r_code = r.get(tel)
            r_code = r_code.decode("utf-8")
            if code is None:
                raise forms.ValidationError("验证码错误!")
            if code != r_code:
                raise forms.ValidationError("验证码填写错误!")
            return code
        else:
            return code


# 登录验证
class MyloginForm(forms.Form):
    tel = forms.CharField(validators=[validators.RegexValidator(r'1[3456789]\d{9}', message='手机号格式不正确')],
                          error_messages={'required': '用户名必须填写'})
    password = forms.CharField(max_length=20, min_length=6,
                               error_messages={'required': '密码必须填写', 'min_length': '密码格式不符合要求'})

    # 综合验证手机号码是否注册过和密码是否正确
    def clean(self):
        data = self.cleaned_data
        # 获取用手机和密码
        tel = data.get('tel')
        password = data.get('password')
        # 验证手机号码是否存在
        if all([tel, password]):
            # 根据手机号码获取用户
            try:
                user = register.objects.get(tel=tel)
            except register.DoesNotExist:
                raise forms.ValidationError({"tel": "该用户不存在!"})

            # 判断密码是否正确
            if user.password != set_password(password):
                raise forms.ValidationError({"password": "密码填写错误!"})

            # 正确
            # 将用户信息保存到data中
            data['user'] = user
            return data
        else:
            return data


# 忘记密码
class ForgetFrom(forms.Form):
    tel = forms.CharField(validators=[validators.RegexValidator(r'1[3456789]\d{9}', message='手机号格式不正确')],
                          error_messages={'required': '手机号必须填写'})
    password = forms.CharField(max_length=20, min_length=6,
                               error_messages={'required': '密码必须填写', 'max_length': '密码不能大于20位',
                                               'min_length': '密码不能少于6位'})
    repassword = forms.CharField(max_length=20, min_length=6,
                                 error_messages={'required': '密码必须填写', 'max_length': '密码不能大于20位',
                                                 'min_length': '密码不能少于6位'})
    code = forms.CharField(error_messages={'required': '验证码必须填写'})

    def clean(self):
        data = self.cleaned_data
        if data.get('password') and data.get('repassword') and data.get('password') != data.get('repassword'):
            raise forms.ValidationError({'repassword': '两次密码不一致'})
        else:
            return data

        # 验证验证码是否正确
    def clean_code(self):
        tel = self.cleaned_data.get("tel")
        code = self.cleaned_data.get('code')
        # 获取redis中的
        r = get_redis_connection("default")
        if tel:
            # 获取 redis中获取的值 是二进制编码,必须解码
            r_code = r.get(tel)
            r_code = r_code.decode("utf-8")
            if code is None:
                raise forms.ValidationError("验证码错误!")
            if code != r_code:
                raise forms.ValidationError("验证码填写错误!")
            return code
        else:
            return code

market/apps/person/views.py
import hashlib
import random
import re
import uuid

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django_redis import get_redis_connection

from order.models import Order_info
from person.forms import MyregisterFrom, MyloginForm, ForgetFrom
from person.helper import set_password, my_login, send_sms

from person.models import register, User_info, Address


def check(old):
    def inner(request, *args, **kwargs):
        id = request.session.get('id')
        if id:
            return old(request, *args, **kwargs)
        else:
            return redirect('person:login')

    return inner


def login(request):
    ''' 登录 '''
    if request.method == 'POST':
        data = request.POST
        form = MyloginForm(data)
        if form.is_valid():
            # tel = form.cleaned_data.get('tel')
            # password = form.cleaned_data.get('password')
            # h = hashlib.md5(password.encode('utf-8'))
            # password = h.hexdigest()
            # data = register.objects.filter(tel=tel, password=password).first()

            # 验证成功后将登陆标识放到session中
            user = form.cleaned_data.get('user')
            # 调用登陆的方法,放在helper模块中的
            my_login(request, user)
            # 跳转到用户中心页面
            next = request.GET.get('next')
            if next:
                return redirect(next)
            else:
                return redirect('person:member')
            # if data:
            #     request.session['id'] = data.id
            #     return redirect('person:member')
            # else:
            #     # 如果找到数据,则进入个人中心.否则,跳转到注册页面
            #     return redirect('person:register')
        else:
            context = {
                'error': form.errors
            }
            return render(request, 'person/login.html', context)

    else:
        return render(request, 'person/login.html')


def myregister(request):
    ''' 注册 '''
    if request.method == 'POST':
        data = request.POST
        form = MyregisterFrom(data)
        if form.is_valid():
            data = form.cleaned_data
            tel = data.get('tel')
            password = data.get('password')
            password = set_password(password)
            register.objects.create(tel=tel, password=password)
            return redirect('person:login')
        else:
            context = {
                'error': form.errors
            }
            return render(request, 'person/reg.html', context)

    else:
        return render(request, 'person/reg.html')


def member(request):
    ''' 用户中心 '''
    id = request.session.get('id')
    if id:
        try:
            data = register.objects.filter(pk=id).first()
            nick = User_info.objects.filter(log_id=id).first()
        except User_info.MultipleObjectsReturned:
            return redirect('person:register')
        except User_info.DoesNotExist:
            return redirect('person:register')
        context = {
            'id': id,
            'data': data,
            'nick': nick
        }
        return render(request, 'person/member.html', context)
    else:
        return render(request, 'person/member.html')


# @check
def info(request):
    ''' 个人资料 '''
    id = request.session.get('id')
    if id:
        if request.method == 'POST':
            nickname = request.POST.get('nickname')
            head_img = request.FILES['head']
            sex = request.POST.get('sex')
            birthday = request.POST.get('birthday')
            school = request.POST.get('school')
            location = request.POST.get('location')
            hometown = request.POST.get('hometown')
            tel = request.POST.get('tel')
            id = register.objects.get(id=id)
            User_info.objects.filter(log_id=id).update(head_img=head_img, nickname=nickname, sex=sex, birthday=birthday,
                                                       school=school,
                                                       location=location,
                                                       hometown=hometown, tel=tel, log_id=id)
            return redirect('person:member')
        else:
            try:
                data = User_info.objects.filter(log_id=id).first()
            except User_info.MultipleObjectsReturned:
                return redirect('person:login')
            except User_info.DoesNotExist:
                return redirect('person:login')
            context = {
                'data': data
            }
            return render(request, 'person/infor.html', context)
    else:
        return render(request, 'person/infor.html')


def forgetpassword(request):
    ''' 忘记密码 '''
    if request.method == 'POST':
        data = request.POST
        form = ForgetFrom(data)
        if form.is_valid():
            tel = form.cleaned_data.get('tel')
            password = form.cleaned_data.get('password')
            h = hashlib.md5(password.encode('utf-8'))
            password = h.hexdigest()
            register.objects.filter(tel=tel).update(password=password)
            return redirect('person:login')
        else:
            context = {
                'error': form.errors
            }
            return render(request, 'person/forgetpassword.html', context)
    else:
        return render(request, 'person/forgetpassword.html')


# 验证码
def send_phone_code(request):
    if request.method == 'POST':
        # 获取手机号码
        tel = request.POST.get('tel')
        # 验证手机号是否正确
        phone_re = re.compile('^1[3-9]\d{9}$')
        res = re.search(phone_re, tel)
        if res:
            # 生成随机验证码
            code = "".join([str(random.randint(0, 9)) for _ in range(4)])
            # print(code)
            # 保存到redis中 ,等你验证的时候使用
            r = get_redis_connection('default')
            r.set(tel, code)
            # 设置过期时间 redis
            r.expire(tel, 120)

            # 发送短信

            # __business_id = uuid.uuid1()
            # params = "{\"code\":\"%s\",\"product\":\"源码超市\"}" % (code,)
            # send_sms(__business_id, tel, "注册验证", "SMS_2245271", params)

            print(code)
            return JsonResponse({"sta": 0})
        else:
            return JsonResponse({"sta": 1, "err": "验证码错误"})

    else:
        return JsonResponse({"sta": 1, "err": "请求方式错误"})


def gladdress(request):
    id = request.session.get('id')
    if id:
        data = Address.objects.filter(log=id, isdelete=False).order_by('-isDefault')
        context = {
            'data': data
        }
        return render(request, 'person/gladdress.html', context)
    else:
        return render(request, 'person/gladdress.html')


def allorder(request):
    id = request.session.get('id')
    order_id = request.GET.get('order_id')
    # Order_info.objects.filter(order_id=order_id).update()
    if id:
        return render(request, 'person/allorder.html')
    else:
        return render(request, 'person/allorder.html')

market/templates/person/forgetpassword.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">忘记密码</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    <input type="text" name="tel" placeholder="请输入手机号" class="login-password">
        <span class="am-text-danger">{{ error.tel }}</span>
    <div class="yzm">
        <input type="text" name = 'code' class="reg-yzm" placeholder="输入验证码"/>
        <input type="button" class="yzm-hq" value="获取验证码"/>
    </div>
    <input type="password" name="password" placeholder="请输入密码" class="login-password">
        <span class="am-text-danger">{{ error.password }}</span>
    <input type="password" name="repassword" placeholder="确认密码" class="login-name">
        <span class="am-text-danger">{{ error.repassword }}</span>
    <input type="submit" class="login-btn" value="立即提交">
    </form>
{% endblock %}

{% block foot_js %}
    <script>
        $(function () {
            $('.yzm-hq').on('click', function () {
                {#获取到手机号码#}
                var tel = $('input[name=tel]').val();
                var rgs = /^1[3-9]\d{9}$/;
                {#console.debug(tel)#}
                var that = this;
                if (!rgs.test(tel)) {
                    alert('手机号码格式不正确')
                }
                else {
                    $.ajax({
                        type: 'post',
                        url: '{% url 'person:send' %}',
                        data: {"tel": tel, "csrfmiddlewaretoken": "{{ csrf_token  }}"},
                        dataType: 'json',
                        success: function (data) {
                                {#console.debug(111)#}
                                if(data.sta == 0){
                                    var count = 60;
                                    $(that).css('background','#ababab');
                                    $(that).attr('disabled','disabled');
                                    var timer = window.setInterval(function () {
                                        --count;
                                        var text = count +'秒后重新发送';
                                        $(that).val(text);
                                        if(count == 0){
                                            $(that).css('background','#76bb2a');
                                            $(that).removeAttr('disabled');
                                            $(that).val('获取验证码');
                                            window.clearInterval(timer)
                                        }
                                    },1000)
                                }
                            }
                        })
                    }
            })
        })
    </script>
{% endblock %}

market/templates/person/gladdress.html
{% extends 'public/base.html' %}
{% load static %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">管理收货地址</a>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="{% url 'order:address' %}" class="">
                <i class="am-icon-plus"></i>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="address-list">
        {% for v in data %}
            <li {% if v.isDefault %}class="curr"{% endif %} liid = {{ v.id }}>
                <p>收货人：{{ v.name }}&nbsp;&nbsp;{{ v.tel }}</p>
                <p class="order-add1">收货地址: {{ v.hcity }}-{{ v.hproper }}-{{ v.harea }}-{{ v.brief }}</p>
                <hr/>
                <div class="address-cz">
                    <label class="am-radio am-warning">
                        <input type="radio" name="radio3" value="" data-am-ucheck
                               {% if v.isDefault %}checked{% endif %} class="def"> 设为默认
                    </label>
                    <a href="{% url 'order:edit' v.id %}"><img src="{% static 'images/bj.png' %}"
                                                               width="18"/>&nbsp;编辑</a>
                    <a href="javascript:;" class="del">删除</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}
{% block foot_js %}
    <script>
        $(function () {
            $(".del").on('click', function () {
                var li = $(this).parents('li');
                var id = li.attr("liid");
                $.ajax({
                    type:'POST',
                    url:"{% url 'order:delete' %}",
                    data:{"id":id,"csrfmiddlewaretoken":"{{ csrf_token }}"},
                    dataType:"json",
                    success:function (data) {
                        if(data.code==0){
                            li.remove()
                        }else{
                            alert("删除失败")
                        }

                    }
                })
            });

            $(".def").on('click', function () {
                var li = $(this).parents('li');
                var id = li.attr("liid");
                $.ajax({
                    type:'POST',
                    url:"{% url 'order:default' %}",
                    data:{"id":id,"csrfmiddlewaretoken":"{{ csrf_token }}"},
                    dataType:"json",
                    success:function (data) {
                        if(data.code==0){
                            $('.address-list li').removeClass("curr");
                            li.addClass("curr");
                            li.find(".def").attr('checked',"checked");
                        }else {
                            alert('修改失败')
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

market/templates/person/member.html
{% extends 'public/base.html' %}
{% load static %}
{% block header %}
    <body style="background: #f6f6f6;">
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <h1 class="am-header-title">
            <a href="" class="">个人中心</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}
{% block content %}
    <div class="member">
        <div class="mem-tit">
            {% if data and nick %}
                {{ nick.nickname }}
            {% endif %}
            {% if nick is None %}
                 {{ data.tel }}
            {% endif %}
            {% if data is none %}
                 <a href="{% url 'person:register' %}">登录/注册</a>
            {% endif %}

            <a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
        </div>
        <div class="mem-pic">
            {% if nick.head_sculpture %}
                <div class="mem-pic-bg" style="background-image: url( {{ MEDIA_URL }}{{ nick.head_img }});"></div>
                {% else %}
                <div class="mem-pic-bg" style="background-image: url({% static 'images/memtx.png' %});"></div>
            {% endif %}
        </div>
        <ul class="member-menu">
            <li>
                <a href="records.html">
                    <p class="yellow">0</p>
                    <p class="black">帐户余额 </p>
                </a>
            </li>
            <li>
                <a href="integral.html">
                    <p class="yellow">0</p>
                    <p class="black">积分 </p>
                </a>
            </li>
            <li>
                <a href="yhq.html">
                    <p class="yellow">0</p>
                    <p class="black">优惠劵 </p>
                </a>
            </li>
            <li>
                <a href="collect.html">
                    <p class="yellow">0</p>
                    <p class="black">我的收藏 </p>
                </a>
            </li>
        </ul>
    </div>
    <div class="user-list">
        <div class="u-list-main">
            <img src="{% static 'images/order-pic.png' %}" width="27"/>
            <span>我的购物订单</span>
            <a href="{% url 'person:allorder' %}">查看全部订单></a>
        </div>
        <ul class="user-nav">
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}">
                <p>待付款</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}">
                <p>待收货</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}">
                <p>待评价</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}">
                <p>退换货</p></a></li>
        </ul>
        <div class="u-list-main">
            <img src="{% static 'images/order-my.png' %}" width="27"/>
            <span>帐户与安全</span>
        </div>
        <ul class="user-nav">
            <li><a href="{% url 'person:info' %}"> <img src="{% static 'images/1-icon4.png' %}">
                <p>个人资料</p></a></li>
            <li><a href="{% url 'person:gladdress' %}"> <img src="{% static 'images/1-icon5.png' %}">
                <p>收货地址</p></a></li>
            <li><a href="saftystep.html"> <img src="{% static 'images/1-icon6.png' %}">
                <p>安全设置</p></a></li>
            <li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}">
                <p>我的钱包</p></a></li>
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav"
        style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
        <li>
            <div class="am-gallery-item">
                <a href="job.html" class="">
                    <img src="{% static 'images/m_03.png' %}"/>
                    <p>我要兼职</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="recommend.html" class="">
                    <img src="{% static 'images/m_04.png' %}"/>
                    <p>推荐有奖</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="myrecommend.html" class="">
                    <img src="{% static 'images/m_05.png' %}"/>
                    <p>我的推荐</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_06.png' %}"/>
                    <p>我的佣金</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/m_02.png' %}"/>
                    <p>我的红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="message.html" class="">
                    <img src="{% static 'images/m_07.png' %}"/>
                    <p>我的动态</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/m_08.png' %}"/>
                    <p>客服中心</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_09.png' %}"/>
                    <p>安全退出</p>
                </a>
            </div>
        </li>
    </ul>
    </div>
    <!--客服中心-->
    <div class="qd-box">
        <div class="popup-title">
            <span>客服中心</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
                <img src="{% static 'images/contactqq.png' %}" width="50"/>
                <p class="contactqq">联系QQ</p>
            </a>
            <a href="tel:0791-12345678">
                <img src="{% static 'images/contacttele.png' %}" width="50"/>
                <p class="contacttele">呼叫电话</p>
            </a>
        </div>
    </div>
    <!--客服中心-->
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:index' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:shopcart' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="{% url 'order:tureorder' %}" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'person:member' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>

{% endblock %}