market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import shopcart, addcart, pay
from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword

urlpatterns = [
    url(r'^shopcart/$', shopcart, name='shopcart'),  # 购物车
    url(r'^addcart/$', addcart, name='addcart'),  #添加购物车
    url(r'^pay/$', pay, name='pay'),  #支付成功
]

market/apps/goods/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from goods.views import index, detail, category, city, village, village_edit

urlpatterns = [
    # 设置缓存
    url(r'^$', cache_page(3600)(index), name='index'),
    url(r'^(?P<id>\d+).html$', detail, name='detail'),
    url(r'^category/(?P<cate_id>\d+)/(?P<order_id>\d)/$', category, name='category'),
    url(r'^city/$', city, name='city'),
    url(r'^village/$', village, name='village'),
    url(r'^village_edit/(?P<id>\d+)/$', village_edit, name='village_edit'),

]

market/apps/order/urls.py
from django.conf.urls import url

from order.views import tureorder, address, add, edit, addedit, delete, default, order,addorder
from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword

urlpatterns = [
    url(r'^tureorder/$', tureorder, name='tureorder'),  # 确认订单
    url(r'^order/$', order, name='order'),  # 确认订单
    url(r'^address/$', address, name='address'),  # 地址
    url(r'^addedit/$', addedit, name='addedit'),  # 地址
    url(r'^add/$', add, name='add'),  # 添加地址
    url(r'^edit/(?P<id>\d+)/$', edit, name='edit'),  # 修改地址
    url(r'^delete/$', delete, name='delete'),  # 删除地址
    url(r'^default/$', default, name='default'),  # 设置为默认值地址
    url(r'^addorder/$', addorder, name='addorder'),  # 设置为默认值地址
]

market/apps/person/urls.py
from django.conf.urls import url

from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword, send_phone_code

urlpatterns = [
    url(r'^login/$', login, name='login'),  # 登录
    url(r'^reg/$', myregister, name='register'),  # 注册
    url(r'^member/$', member, name='member'),  # 个人中心
    url(r'^allorder/$', allorder, name='allorder'),  # 订单
    url(r'^gladdress/$', gladdress, name='gladdress'),  # 地址
    url(r'^info/$', info, name='info'),  # 个人资料
    url(r'^forget/$', forgetpassword, name='forget'),  # 忘记密码
    url(r'^send/$', send_phone_code, name='send'),  # 验证码
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    url(r'^person/', include('person.urls', namespace='person')),
    url(r'^index/', include('goods.urls', namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
]

market/apps/goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.db import models

from db.commonmodel import Basemodels


# 轮播图
class Ad(Basemodels):
    name = models.CharField(max_length=100, verbose_name='轮播名称')
    sku = models.ForeignKey(to='SKU', verbose_name='sku_id')
    img = models.ImageField(upload_to='goods/%Y%m', default='goods/banner.png ', verbose_name='图片地址')
    order = models.IntegerField(verbose_name='排序')

    class Meta:
        db_table = 'ad'
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 活动表
class Active(Basemodels):
    name = models.CharField(max_length=200, verbose_name='活动名称')
    img = models.ImageField(upload_to='goods/%Y%m', default='goods/s2.png ', verbose_name='图片地址')
    url = models.CharField(max_length=200, verbose_name='跳转的界面地址')
    sku = models.ForeignKey(to='SKU', verbose_name='sku_id')

    class Meta:
        db_table = 'active'
        verbose_name = '商品活动表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 活动专区
class Actarea(Basemodels):
    name = models.CharField(max_length=200, verbose_name='活动名称')
    comment = models.CharField(max_length=200, verbose_name='活动描述')
    order = models.IntegerField(verbose_name='排序')
    is_up = models.BooleanField(default=True, verbose_name='是否上架')

    class Meta:
        db_table = 'actarea'
        verbose_name = '活动专区'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 活动专区商品
class Actgoods(Basemodels):
    actarea = models.ForeignKey(to='Actarea', verbose_name='活动专区id')
    sku = models.ForeignKey(to='SKU', verbose_name='商品id')

    class Meta:
        db_table = 'actgoods'
        verbose_name = '活动专区商品'
        verbose_name_plural = verbose_name


# 分类表
class Category(Basemodels):
    catename = models.CharField(max_length=30, verbose_name='分类名')
    comment = models.TextField(verbose_name='分类描述')

    class Meta:
        db_table = 'category'
        verbose_name = '商品分类表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.catename


# 商品SKU表
class SKU(Basemodels):
    choices = (
        (1, '斤'),
        (2, '件'),
        (3, '箱'),
    )
    name = models.CharField(max_length=100, verbose_name='商品名')
    introduction = models.TextField(verbose_name='商品简介')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='价格')
    unit = models.SmallIntegerField(choices=choices, verbose_name='单位')
    stock = models.IntegerField(verbose_name='库存')
    sell = models.IntegerField(verbose_name='销量')
    img = models.ImageField(upload_to='goods/%Y%m', default='goods/s2.png ', verbose_name='图片logo地址')

    def logo(self):
        return '<img src="{}{}" style="width:30px">'.format(settings.MEDIA_URL, self.img)

    logo.allow_tags = True
    logo.short_description = 'LOGO'

    is_up = models.BooleanField(default=True, verbose_name='是否上架')
    cate = models.ForeignKey(to='Category', verbose_name='分类id')
    spu = models.ForeignKey(to='SPU', verbose_name='spu_id')

    class Meta:
        db_table = 'SKU'
        verbose_name = '商品SKU表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 商品SPU表
class SPU(models.Model):
    name = models.CharField(max_length=200, verbose_name='spu名称')
    content = RichTextUploadingField(verbose_name='商品详情')

    class Meta:
        db_table = 'SPU'
        verbose_name = '商品SPU表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 商品相册
class GoodsImg(Basemodels):
    img = models.ImageField(upload_to='goods/%Y%m', default='goods/pic.png ', verbose_name='商品图片地址')
    sku = models.ForeignKey(to='SKU', verbose_name='sku_id')

    class Meta:
        db_table = ' goodsimg'
        verbose_name = '商品相册表'
        verbose_name_plural = verbose_name

market/apps/goods/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, redirect

from goods.models import Ad, Active, Actarea, Actgoods, Category, SKU
from django_redis import get_redis_connection


def index(request):
    # 轮播图
    banner = Ad.objects.filter()

    # 不规则活动
    act = Active.objects.all()

    # 特色专区
    actarea = Actarea.objects.all()

    context = {
        'banner': banner,
        'act': act,
        'actarea': actarea,
    }
    return render(request, 'goods/index.html', context)


def detail(request, id):
    sku = SKU.objects.get(id=id)
    context = {
        'sku': sku
    }
    return render(request, 'goods/detail.html', context)


def category(request, cate_id=0, order_id=0):
    # # 分类区
    # cate = Category.objects.filter()
    #
    # # 默认显示第一个
    # id = cate.first().id
    # # 商品列表
    # g_id = request.GET.get('id',default=id)
    #
    # # print(g_id)
    # cate1 = Category.objects.get(pk=g_id)
    # goodlist = cate1.sku_set.all().values()
    # data_dict_list = list(goodlist)
    #
    # context = {
    #     'cate': cate,
    #     'goodlist': goodlist,
    # }
    # if request.is_ajax():
    #     return JsonResponse({'list': data_dict_list})
    #
    # 获取到所有的分类
    category = Category.objects.filter()
    # 转换接收到分类id,如果不存在跳转到首页
    try:
        cate_id = int(cate_id)
        order_id = int(order_id)
    except:
        return redirect('goods:index')

    # 输入的值为0,返回第一个分类数据,分类id为第一个分类数据的id,否则等于收到的id值
    if cate_id == 0:
        cate = category.first()
        cate_id = cate.id
    else:
        cate = Category.objects.get(pk=cate_id)
    # 获取分类下的商品

    # 根据选择的排序id来排序
    order_rule = ['id', '-sell', '-price', 'price', '-add_time']
    try:
        order = order_rule[order_id]
    except:
        order = order_rule[0]
    goodlist = cate.sku_set.all()
    goodlist = goodlist.order_by(order)

    # 分页
    paginator = Paginator(goodlist, 2)
    page = request.GET.get('p', 1)
    try:
        goodlist = paginator.page(page)
    except PageNotAnInteger:
        goodlist = paginator.page(1)
    except EmptyPage:
        goodlist = paginator.page(paginator.num_pages)

    cartcount = 0
    if request.session.get("id"):
        user_id = request.session.get("id")
        r = get_redis_connection('default')
        user_key = "user_key_{}".format(user_id)
        count = r.hvals(user_key)
        for v in count:
            cartcount += int(v)

    context = {
        'category': category,
        'cate_id': cate_id,
        'goodlist': goodlist,
        'order_id': order_id,
        "count": cartcount
    }
    return render(request, 'goods/category.html', context)


def city(request):
    return render(request, 'goods/city.html')


def village(request):
    return render(request, 'goods/village.html')


def village_edit(request, id):
    context = {
        "id": id
    }
    return render(request, 'goods/village_edit.html', context)

market/templates/goods/category.html
{% extends 'public/base.html' %}
{% load static %}
{% block meta_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }
    </style>

{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <div class="cate-search">
            <form action="/search/" method="get">
                <input type="text" name="q" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
                <input type="submit" class="cate-btn" value=""/>
            </form>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="list-nav" id="order">
        <li {% if order_id == 0 %} class="current" {% endif %}><a href="{% url 'goods:category' cate_id 0 %}">综合</a>
        </li>
        <li {% if order_id == 1 %} class="current" {% endif %}><a href="{% url 'goods:category' cate_id 1 %}">销量</a>
        </li>
        <li {% if order_id == 2 %} class="current" {% endif %}><a href="{% url 'goods:category' cate_id 2 %}"><i
                class="list-price">价格</i></a></li>
        <li {% if order_id == 4 %} class="current" {% endif %}><a href="{% url 'goods:category' cate_id 4 %}">新品</a>
        </li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for cate in category %}
                <li {% if cate.id == cate_id %}class="current" {% endif %}><a
                        href="{% url 'goods:category' cate.id order_id %}" class="cate">{{ cate.catename }}</a></li>
            {% endfor %}
        </div>

        <div class="list-right">
            <ul class="list-pro" id="goodslist">
                {% for v in goodlist %}
                    <li>
                        <a href="{% url 'goods:detail' v.id %}" class="img"><img src="{{ MEDIA_URL }}{{ v.img }}"
                                                                                 class="list-pic"/></a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit"><a href="{% url 'goods:detail' v.id %}" class="name">{{ v.name }}</a></div>
                            <div class="am-gallery-desc" class="price">{{ v.price }}</div>
                            <p class="sell">销量：{{ v.sell }}件</p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input id="num" readonly="" sku_id="{{ v.id }}" class="text_box" name="" type="text"
                                       value="0"/>
                                <a class="increase">+</a>
                            </div>
                        </div>
                        <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                    </li>
                {% endfor %}
                <hr>
                {% if goodlist.has_previous %}
                    <span><a href="?p={{ goodlist.previous_page_number }}">上一页</a></span>
                {% endif %}
                {% if goodlist.has_next %}
                    <span><a href="?p={{ goodlist.next_page_number }}">下一页</a></span>
                {% endif %}
            </ul>
        </div>

    </div>

{% endblock %}

{% block foot %}
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <a href="{% url 'cart:shopcart' %}">
            <div class="fix-bot-cart"><i>{{ count }}</i></div>
        </a>
        <a href="{% url 'order:tureorder' %}" class="list-js">去结算</a>
        <a href="{% url 'order:tureorder' %}" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}
<!--底部-->

{% block foot_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var sku_id = $("#num").attr('sku_id');
                var current_num = parseInt(self.siblings('input').val());

                var num = 1;
                $.ajax({
                    type: "POST",
                    url: "{% url 'cart:addcart' %}",
                    data: {"sku_id": sku_id, "num": num, "csrfmiddlewaretoken": "{{ csrf_token  }}"},
                    dataType: "json",
                    success: function (data) {
                        if (data.code == 1) {
                            var flag = confirm("未登录,是否要跳转到登录界面");
                            if (flag) {
                                location.href = "{% url 'person:login' %}?next={% url 'goods:category' cate_id order_id %}"
                            }
                        } else if (data.code == 0) {
                            current_num += 1;
                            if (current_num > 0) {
                                self.siblings(".decrease").fadeIn();
                                self.siblings(".text_box").fadeIn();
                            }
                            self.siblings('input').val(current_num);
                            $(".fix-bot-cart i").text(data.total);
                        }
                    }
                });
            });

            $('.decrease').click(function () {
                var self = $(this);
                var sku_id = $("#num").attr('sku_id');
                var current_num = parseInt(self.siblings('input').val());
                var num = -1;
                if (current_num > 0) {
                    $.ajax({
                        type: "POST",
                        url: "{% url 'cart:addcart' %}",
                        data: {"sku_id": sku_id, "num": num, "csrfmiddlewaretoken": "{{ csrf_token  }}"},
                        dataType: "json",
                        success: function (data) {
                            if (data.code == 1) {
                                var flag = confirm("未登录,是否要跳转到登录界面");
                                if (flag) {
                                    location.href = "{% url 'person:login' %}?next={% url 'goods:category' cate_id order_id %}"
                                }
                            } else if (data.code == 0) {
                                current_num -= 1;
                                if (current_num < 1) {
                                    self.fadeOut();
                                    self.siblings(".text_box").fadeOut();
                                }
                                self.siblings('input').val(current_num);
                                $(".fix-bot-cart i").text(data.total)
                            }
                        }
                    });
                }
            });

            if ("{{ order_id }}" == 2) {
                $('.list-price').parent("a").attr('href', '{% url 'goods:category' cate_id 3 %}')
            } else if ("{{ order_id }}" == 3) {
                $('.list-price').parent("a").attr('href', '{% url 'goods:category' cate_id 2 %}')
            }
        })

    </script>
{% endblock %}

market/templates/goods/city.html
{% extends 'public/base.html' %}
{% load static %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">选择城市</a>
            </h1>
	    </header>
{% endblock %}
{% block content %}
    <div style="height: 49px;"></div>
	    <ul class="city-list">
	    	<li class="curr"><a href="">成都</a></li>
	    	<li><a href="">长沙</a></li>
	    	<li><a href="">北京</a></li>
	    </ul>
{% endblock %}

market/templates/goods/index.html
{% extends 'public/base.html' %}
{% load static %}
{% block meta_css %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <title>根据ip定位</title>
    <link rel="stylesheet" href="https://a.amap.com/jsapi_demos/static/demo-center/css/demo-center.css"/>
    <style type="text/css">
        html, body, #container {
            height: 100%;
        }
    </style>
{% endblock %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head1">
        <div class="am-header-left am-header-nav">
            <a href="{% url 'goods:city' %}" class="" style="color: #fff;">
                <img src="{% static 'images/city.png' %}" id="location"/>
                <p style="font-size: 12px; margin-top: -35px;" id='info'></p>
            </a>
        </div>
        <h1 class="am-header-title1">
            <div class="search-box">
                <a href="{% url 'goods:village' %}" class="index-search">源码时代成都校区∨</a>
                <!--  <input type="submit" value="" class="search-icon" /> -->
            </div>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="tidings.html" class="">
                <div class="messgae"><span>10</span></div>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for ban in banner %}
                <li><img src="{{ MEDIA_URL }}{{ ban.img }}"/></li>
            {% endfor %}
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav">
        <li>
            <div class="am-gallery-item">
                <a href="recharge.html" class="">
                    <img src="{% static 'images/icon.png' %}"/>
                    <p>充值</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/icon1.png' %}"/>
                    <p>签到</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/icon2.png' %}"/>
                    <p>红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/icon3.png' %}"/>
                    <p>即将上线</p>
                </a>
            </div>
        </li>
    </ul>
    <ul class="sq-nav1">
        <li>
            <div class="am-gallery-item">
                <a href="speed.html" class="">
                    <img src="{% static 'images/icon4.png' %}"/>
                    <p>零食飞速</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'goods:category' 0 0 %}" class="">
                    <img src="{% static 'images/icon5.png' %}"/>
                    <p>超市</p>
                </a>
            </div>
        </li>

    </ul>
    <div class="h-line"></div>
    <!--不规则展示-->
    <div class="index-product">
        <div class="index-pro-lf"><a href=""><img src="{{ MEDIA_URL }}{{ act.0.img }}"/></a></div>
        <div class="index-pro-lr"><a href=""><img src="{{ MEDIA_URL }}{{ act.1.img }}"/></a></div>
    </div>
    <div class="product-bot">
        <div class="product-bot-lf"><a href=""><img src="{{ MEDIA_URL }}{{ act.2.img }}"/></a></div>
        <div class="product-bot-lr">
            <div class="top"><a href=""><img src="{{ MEDIA_URL }}{{ act.3.img }}"/></a></div>
            <div class="bot">
                <div class="bot-lf"><a href=""><img src="{{ MEDIA_URL }}{{ act.4.img }}"/></a></div>
                <div class="bot-lr"><a href=""><img src="{{ MEDIA_URL }}{{ act.5.img }}"/></a></div>
            </div>
        </div>
    </div>
    <!--不规则展示-->
    <div class="h-line"></div>
    <!-- 特色专区-->
    {% for area in actarea %}
        <div class="sq-title">
            <img src="{% static 'images/ts.png' %}" width="26"/>
            {{ area.name }}
        </div>

        <ul data-am-widget="gallery" class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default">

            {% for actgoods in area.actgoods_set.all %}
                <li>
                    <div class="am-gallery-item">
                        <a href="{% url 'goods:detail' actgoods.sku.pk %}" class="">
                            <img src=" {{ MEDIA_URL }}{{ actgoods.sku.img }}"/>
                            <h3 class="am-gallery-title">{{ actgoods.sku.spu.name }}{{ actgoods.sku.name }}</h3>
                            <div class="am-gallery-desc">￥{{ actgoods.sku.price }}</div>
                        </a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
    <!--签到-->
    <div class="qd-box">
        <div class="popup-title">
            <span>签到成功</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <img src="{% static 'images/qiandao.png' %}" width="40"/>&nbsp; 您已连续签到3天
        </div>
    </div>
    <!--签到-->
{% endblock %}
{% block foot %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'goods:index' %}" class="curr">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cart:shopcart' %}" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'person:member' %}" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>


{#定位#}
<script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.10&key=7204bc8ae2de8a23baa3790c30176fef&plugin=AMap.CitySearch"></script>
<script type="text/javascript">
    //获取用户所在城市信息
    function showCityInfo() {
        //实例化城市查询类
        var citysearch = new AMap.CitySearch();
        //自动获取用户IP，返回当前城市
        citysearch.getLocalCity(function(status, result) {
            if (status === 'complete' && result.info === 'OK') {
                if (result && result.city && result.bounds) {
                    var cityinfo = result.city;
                    var citybounds = result.bounds;
                    document.getElementById('info').innerHTML = cityinfo;
                    //地图显示当前城市
                    map.setBounds(citybounds);
                }
            } else {
                document.getElementById('info').innerHTML = result.info;
            }
        });
    }
    showCityInfo();
</script>
{% endblock %}

{% block foot_js %}
    <script type='text/javascript'>
        (function () {
            new PopUp_api({el: '.index-qd', html: '.qd-box'});
        })()
    </script>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/amazeui.min.js' %}"></script>

{% endblock %}

market/templates/goods/location.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <title>根据ip定位</title>
    <link rel="stylesheet" href="https://a.amap.com/jsapi_demos/static/demo-center/css/demo-center.css"/> 
    <style type="text/css">
       html,body,#container{
           height:100%;
       }
    </style>
</head>
<body>
<div class="info">
    <p id='info'></p>
</div>
<script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.10&key=7204bc8ae2de8a23baa3790c30176fef&plugin=AMap.CitySearch"></script>
<script type="text/javascript">
    //获取用户所在城市信息
    function showCityInfo() {
        //实例化城市查询类
        var citysearch = new AMap.CitySearch();
        //自动获取用户IP，返回当前城市
        citysearch.getLocalCity(function(status, result) {
            if (status === 'complete' && result.info === 'OK') {
                if (result && result.city && result.bounds) {
                    var cityinfo = result.city;
                    var citybounds = result.bounds;
                    document.getElementById('info').innerHTML = '您当前所在城市：'+cityinfo;
                    //地图显示当前城市
                    map.setBounds(citybounds);
                }
            } else {
                document.getElementById('info').innerHTML = result.info;
            }
        });
    }
    showCityInfo();
</script>
</body>
</html>