market/apps/cart/urls.py
from django.conf.urls import url

from cart.views import shopcart, addcart, pay
from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword

urlpatterns = [
    url(r'^shopcart/$', shopcart, name='shopcart'),  # 购物车
    url(r'^addcart/$', addcart, name='addcart'),  #添加购物车
    url(r'^pay/$', pay, name='pay'),  #支付成功
]

market/apps/goods/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from goods.views import index, detail, category, city, village, village_edit

urlpatterns = [
    # 设置缓存
    url(r'^$', cache_page(3600)(index), name='index'),
    url(r'^(?P<id>\d+).html$', detail, name='detail'),
    url(r'^category/(?P<cate_id>\d+)/(?P<order_id>\d)/$', category, name='category'),
    url(r'^city/$', city, name='city'),
    url(r'^village/$', village, name='village'),
    url(r'^village_edit/(?P<id>\d+)/$', village_edit, name='village_edit'),

]

market/apps/order/urls.py
from django.conf.urls import url

from order.views import tureorder, address, add, edit, addedit, delete, default, order,addorder
from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword

urlpatterns = [
    url(r'^tureorder/$', tureorder, name='tureorder'),  # 确认订单
    url(r'^order/$', order, name='order'),  # 确认订单
    url(r'^address/$', address, name='address'),  # 地址
    url(r'^addedit/$', addedit, name='addedit'),  # 地址
    url(r'^add/$', add, name='add'),  # 添加地址
    url(r'^edit/(?P<id>\d+)/$', edit, name='edit'),  # 修改地址
    url(r'^delete/$', delete, name='delete'),  # 删除地址
    url(r'^default/$', default, name='default'),  # 设置为默认值地址
    url(r'^addorder/$', addorder, name='addorder'),  # 设置为默认值地址
]

market/apps/person/urls.py
from django.conf.urls import url

from person.views import login, myregister, member, allorder, gladdress, info, forgetpassword, send_phone_code

urlpatterns = [
    url(r'^login/$', login, name='login'),  # 登录
    url(r'^reg/$', myregister, name='register'),  # 注册
    url(r'^member/$', member, name='member'),  # 个人中心
    url(r'^allorder/$', allorder, name='allorder'),  # 订单
    url(r'^gladdress/$', gladdress, name='gladdress'),  # 地址
    url(r'^info/$', info, name='info'),  # 个人资料
    url(r'^forget/$', forgetpassword, name='forget'),  # 忘记密码
    url(r'^send/$', send_phone_code, name='send'),  # 验证码
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    url(r'^person/', include('person.urls', namespace='person')),
    url(r'^index/', include('goods.urls', namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
]

market/apps/order/models.py
from django.db import models

from db.commonmodel import Basemodels


class Paymethod(Basemodels):
    pay_name = models.CharField(verbose_name='支付方式', max_length=20)
    logo = models.ImageField(upload_to='pay/', verbose_name='logo')

    class Meta:
        db_table = 'paymethod'
        verbose_name = "支付方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.pay_name


class Transport(Basemodels):
    name = models.CharField(verbose_name='配送方式', max_length=20)
    money = models.DecimalField(verbose_name='金额', max_digits=9, decimal_places=2, default=0)

    class Meta:
        db_table = 'transport'
        verbose_name = "配送方式"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Order_info(Basemodels):
    choices = [
        (0, '待付款'),
        (1, '退发货'),
        (2, '待收货'),
        (3, '待评价'),
        (4, '已完成'),
    ]
    ordernum = models.CharField(max_length=255, verbose_name='订单编号', default=0)
    user = models.ForeignKey(to="person.register", verbose_name='用户id')
    name = models.CharField(max_length=30, verbose_name='收货人姓名')
    tel = models.CharField(max_length=11, verbose_name='收货人电话')
    address = models.CharField(max_length=200, verbose_name='地址信息')
    order_status = models.SmallIntegerField(choices=choices, default=0, verbose_name='订单状态')
    transport = models.CharField(max_length=30, verbose_name='运输方式')
    trans_money = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='运输金额')
    paymethod = models.ForeignKey(to='Paymethod', verbose_name='支付方式id', null=True, blank=True)
    order_money = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='订单商品金额', default=0)
    total = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='订单总金额', default=0)
    real_money = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='实付金额')
    comment = models.CharField(max_length=255, verbose_name='备注', null=True, blank=True)

    class Meta:
        db_table = 'order_info'
        verbose_name = '订单信息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ordernum


class Order_goods(Basemodels):
    order = models.ForeignKey(to='Order_info', verbose_name='订单id')
    sku = models.ForeignKey(to='goods.SKU', verbose_name='商品sku_id')
    number = models.IntegerField(verbose_name='商品数量')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='商品价格')

    class Meta:
        db_table = 'order_goods'
        verbose_name = '订单商品表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku

market/apps/order/forms.py
from django import forms

from person.models import Address


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['add_time', 'update_time', 'isdelete', 'log']

        error_messages = {
            'name': {
                'required': "请填写用户名！",
            },
            'tel': {
                'required': "请填写手机号码！",
            },
            'brief': {
                'required': "请填写详细地址！",
            },
            'hcity': {
                'required': "请填写完整地址！",
            },
            'hproper': {
                'required': "请填写完整地址！",
            },
            'harea': {
                'required': "请填写完整地址！",
            },
        }

    def clean(self):
        user_id = self.data.get('id')
        count = Address.objects.filter(log_id=user_id, isdelete=False).count()
        if count >= 6:
            raise forms.ValidationError('地址不能超过6个')

        isDefault = self.cleaned_data.get('isDefault')
        if isDefault:
            Address.objects.filter(log_id=user_id).update(isDefault=False)
        return self.cleaned_data


class AddresseditForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['add_time', 'update_time', 'isdelete', 'log']

        error_messages = {
            'name': {
                'required': "请填写用户名！",
            },
            'tel': {
                'required': "请填写手机号码！",
            },
            'brief': {
                'required': "请填写详细地址！",
            },
            'hcity': {
                'required': "请填写完整地址！",
            },
            'hproper': {
                'required': "请填写完整地址！",
            },
            'harea': {
                'required': "请填写完整地址！",
            },
        }

    def clean(self):
        user_id = self.data.get('id')

        isDefault = self.cleaned_data.get('isDefault')
        if isDefault:
            Address.objects.filter(log_id=user_id).update(isDefault=False)
        return self.cleaned_data

market/apps/order/views.py
import os
import random

from django.db import transaction
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django_redis import get_redis_connection

from goods.models import SKU
from market.settings import BASE_DIR
from order.forms import AddressForm, AddresseditForm
from order.models import Transport, Order_info, Order_goods
from person.models import Address

from datetime import datetime

# 地址三级联动
# from utils.alipay.alipay import AliPay
from alipay import AliPay

def address(request):
    if request.method == "POST":
        data = request.POST
        hcity = data.get('hcity')
        hproper = data.get('hproper')
        harea = data.get('harea')
        context = {
            'hcity': hcity,
            'hproper': hproper,
            'harea': harea,
        }
        return render(request, 'order/address.html', context)
    else:
        return render(request, 'order/address.html')


def addedit(request):
    if request.method == "POST":
        data = request.POST
        id = data.get('id')
        # print(id)
        address = Address.objects.get(pk=id)
        hcity = data.get('hcity')
        hproper = data.get('hproper')
        harea = data.get('harea')
        context = {
            'id': id,
            'hcity': hcity,
            'hproper': hproper,
            'harea': harea,
            'address': address
        }
        return render(request, 'order/address_edit.html', context)
    else:
        return render(request, 'order/address_edit.html')


# 添加地址
def add(request):
    if request.method == "POST":
        id = request.session.get('id')
        data = request.POST.dict()
        data['id'] = id
        form = AddressForm(data)
        # print(data.isDefault)
        if form.is_valid():
            data = form.cleaned_data
            data["log_id"] = id
            Address.objects.create(**data)
            return redirect('person:gladdress')
        else:
            context = {
                'error': form.errors,
                'form': form
            }
            return render(request, 'order/address.html', context)
    else:
        return render(request, 'order/address.html')


# 修改地址
def edit(request, id):
    if request.method == "GET":
        log_id = request.session.get('id')
        try:
            address = Address.objects.get(pk=id, log_id=log_id)
        except Address.DoesNotExist:
            return redirect('person:gladdress')
        # print(address.isDefault)
        context = {
            "address": address,
            'id': address.id
        }
        return render(request, 'order/address_edit.html', context)
    else:
        log_id = request.session.get('id')
        data = request.POST.dict()
        data['id'] = id
        form = AddresseditForm(data)
        # print(data)
        if form.is_valid():
            data = form.cleaned_data
            Address.objects.filter(log_id=log_id).update(isDefault=False)
            Address.objects.filter(pk=id, log_id=log_id).update(**data)
            return redirect('person:gladdress')
        else:
            context = {
                'error': form.errors,
                'form': form
            }
            return render(request, 'order/address.html', context)


def delete(request):
    log_id = request.session.get('id')
    if request.method == "POST":
        id = request.POST.get("id")
        Address.objects.filter(pk=id, log_id=log_id).update(isdelete=True)
        return JsonResponse({"code": 0})
    else:
        return JsonResponse({"code": 1, "err": "请求方式错误"})


def default(request):
    log_id = request.session.get('id')
    if request.method == "POST":
        id = request.POST.get("id")
        Address.objects.filter(log_id=log_id).update(isDefault=False)
        Address.objects.filter(pk=id, log_id=log_id).update(isDefault=True)
        return JsonResponse({"code": 0})
    else:
        return JsonResponse({"code": 1, "err": "请求方式错误"})


# 添加订单
def addorder(request):
    id = request.session.get('id')
    goods = request.POST.get('goods')
    r = get_redis_connection('default')
    goods = goods.strip(" ")
    goods = goods.split(" ")
    order_key = "order_key_{}".format(id)
    user_key = "user_key_{}".format(id)
    r.delete(order_key)
    for sku_id in goods:
        num = r.hget(user_key, sku_id)
        num = int(num)
        r.hset(order_key, sku_id, num)
    return JsonResponse({"code": 0})


# 购物车
@transaction.atomic
def tureorder(request):
    if request.method == 'POST':
        # 是否登录
        id = request.session.get("id")
        if id is None:
            return JsonResponse({"code": 1, "err": "用户没有登录"})

        address = request.POST.get('address')
        sku_id = request.POST.getlist("sku_id")
        transport = request.POST.get("transport")
        comment = request.POST.get('comment')

        # 参数是否都存在
        if not (address and sku_id and transport):
            return JsonResponse({"code": 2, "err": "参数错误"})

        # 参数是否符合要求
        try:
            address = int(address)
            transport = int(transport)
            sku = [int(sku) for sku in sku_id]
        except:
            return JsonResponse({"code": 3, "err": "参数错误"})

        # 所传信息是否存在
        try:
            address = Address.objects.get(pk=address)
        except address.DoesNotExist:
            return JsonResponse({"code": 4, "err": "地址不存在"})

        try:
            transport = Transport.objects.get(pk=transport)
        except transport.DoesNotExist:
            return JsonResponse({"code": 5, "err": "运输方式不存在"})

        # 设置保存点
        # sid = transaction.savepoint()
        # 保存订单信息
        r = get_redis_connection('default')
        user_key = "user_key_{}".format(id)
        time = datetime.now().strftime("%Y%m%d%H%M%S")
        ordernum = "{}{}{}".format(time, id, random.randint(1000, 99999))
        address_brief = "{}{}{}{}".format(address.hcity, address.hproper, address.harea, address.brief)
        # 存储订单信息表
        order = Order_info.objects.create(
            ordernum=ordernum,
            user_id=id,
            name=address.name,
            tel=address.tel,
            address=address_brief,
            transport=transport.name,
            trans_money=transport.money,
        )
        order_money = 0
        total = 0
        for sku_id in sku:
            try:
                goodssku = SKU.objects.select_for_update().get(pk=sku_id, isdelete=False, is_up=True)
            except SKU.DoesNotExist:
                # transaction.savepoint_commit(sid)
                return JsonResponse({"code": 6, "err": "商品不存在"})

            # 获取商品的数量
            count = r.hget(user_key, sku_id)
            count = int(count)
            # 保存订单商品信息
            Order_goods.objects.create(
                order=order,
                sku=goodssku,
                number=count,
                price=goodssku.price
            )
            # 检查库存是否充足
            if goodssku.stock < count:
                # transaction.savepoint_commit(sid)
                return JsonResponse({"code": 7, "err": "库存不足"})
            # 销量增加,库存减少
            goodssku.sell += count
            goodssku.stock -= count

            # 计算商品价格
            order_money += goodssku.price * count

        # 计算总金额
        total += order_money + transport.money

        # 保存价格和备注信息
        try:
            order.order_money = order_money
            order.total = total
            order.comment = comment
            order.save()
        except:
            # 回滚事务
            # transaction.savepoint_commit(sid)
            return JsonResponse({"code": 8, "err": "总价保存失败"})
        # 删除购物车的商品信息

        r.hdel(user_key, *sku)
        # 提交事务
        # transaction.commit(sid)
        return JsonResponse({"code": 0, "ordernum": ordernum})

    else:
        id = request.session.get('id')
        r = get_redis_connection('default')
        goodslist = []
        order_key = "order_key_{}".format(id)
        goods = r.hgetall(order_key)
        price = 0
        for sku_id in goods:
            sku = SKU.objects.get(pk=sku_id)
            r = get_redis_connection('default')
            num = r.hget(order_key, sku_id)
            try:
                sku.num = int(num)
            except:
                return redirect("cart:shopcart")
            # 计算总价
            price += sku.price * sku.num
            goodslist.append(sku)
        transport = Transport.objects.all().order_by('money')
        address = Address.objects.filter(log_id=id, isdelete=False).order_by("isDefault").first()
        context = {
            "address": address,
            "goodslist": goodslist,
            "transport": transport,
        }
        return render(request, 'cart/tureorder.html', context)


def order(request):
    if request.method == "POST":
        order_id = request.POST.get("order")
        order = Order_info.objects.get(pk=order_id)
        price = str(order.total)

        app_private_key_string = open(os.path.join(BASE_DIR, 'apps/utils/alipay/ying_yong_si_yao.txt')).read()
        alipay_public_key_string = open(os.path.join(BASE_DIR, 'apps/utils/alipay/ying_yong_gong_yao.txt')).read()

        alipay = AliPay(
            appid="2016092400584100",
            app_notify_url=None,  # 默认回调url
            app_private_key_string=app_private_key_string,
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            alipay_public_key_string=alipay_public_key_string,
            sign_type="RSA2",  # RSA 或者 RSA2
            debug=True  # 默认False
        )

        order_string = alipay.api_alipay_trade_wap_pay(
            out_trade_no=order.ordernum,
            total_amount=price,
            subject="超市支付",
            return_url="http://127.0.0.1:8000/cart/pay/",
            notify_url=None  # 可选, 不填则使用默认notify url
        )
        re_url = "https://openapi.alipaydev.com/gateway.do?{data}".format(data=order_string)

        # 电脑版
        # """支付请求过程"""
        # # 传递参数初始化支付类

market/templates/order/address.html
{% extends 'public/base.html' %}
{% load static %}

{% block meta_css %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>jQuery手机省市区三级联动城市选择代码</title>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <script src="{% static 'js/Popt.js' %}"></script>
    <script src="{% static 'js/cityJson.js' %}"></script>
    <script src="{% static 'js/citySet.js' %}"></script>

    <style type="text/css">
        ._citys {
            width: 100%;
            height: 100%;
            display: inline-block;
            position: relative;
        }

        ._citys span {
            color: #56b4f8;
            height: 15px;
            width: 15px;
            line-height: 15px;
            text-align: center;
            border-radius: 3px;
            position: absolute;
            right: 1em;
            top: 10px;
            border: 1px solid #56b4f8;
            cursor: pointer;
        }

        ._citys0 {
            width: 100%;
            height: 34px;
            display: inline-block;
            border-bottom: 2px solid #56b4f8;
            padding: 0;
            margin: 0;
        }

        ._citys0 li {
            float: left;
            height: 34px;
            line-height: 34px;
            overflow: hidden;
            font-size: 15px;
            color: #888;
            width: 80px;
            text-align: center;
            cursor: pointer;
        }

        .citySel {
            background-color: #56b4f8;
            color: #fff !important;
        }

        ._citys1 {
            width: 100%;
            height: 80%;
            display: inline-block;
            padding: 10px 0;
            overflow: auto;
        }

        ._citys1 a {
            height: 35px;
            display: block;
            color: #666;
            padding-left: 6px;
            margin-top: 3px;
            line-height: 35px;
            cursor: pointer;
            font-size: 13px;
            overflow: hidden;
        }

        ._citys1 a:hover {
            color: #fff;
            background-color: #56b4f8;
        }

        .ui-content {
            border: 1px solid #EDEDED;
        }

        li {
            list-style-type: none;
        }
    </style>

{% endblock %}

{% block meat_js %}
    <script src="{% static 'js/area.js' %}"></script>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">新增收货地址</a>
        </h1>
    </header>
{% endblock %}
{% block content %}
    <div style="height: 60px;"></div>
    <form action="{% url 'order:add' %}" method="post">
        <ul class="address">
            {% csrf_token %}
            <li>
                <input type="text" name="hcity" value="{{ hcity }}" class="add-input" placeholder="省"/>
                <a href="{% url 'goods:village' %}">
                    <i class="am-icon-angle-right" style="float: right; margin-top: 5px;"></i></a>
            </li>
            <p style="color: red">{{ error.hcity.0 }}</p>
            <li>
                <input type="text" name="hproper" value="{{ hproper }}" class="add-input" placeholder="市"/>
            </li>
            <p style="color: red">{{ error.hproper.0 }}</p>
            <li><input type="text" name="harea" class="add-input" value="{{ harea }}" placeholder="区"/></li>
            <p style="color: red">{{ error.harea.0 }}</p>
            <li><input type="text" name="brief" class="add-input" value="{{ brief }}" placeholder="详细地址"/></li>
            <p style="color: red">{{ error.brief.0 }}</p>
            <li><input type="text" name="name" class="add-input" value="{{ name }}" placeholder="收货人"/></li>
            <p style="color: red">{{ error.name.0 }}</p>
            <li><input type="text" name="tel" class="add-input" value="{{ tel }}" placeholder="13000000000"/></li>
            <p style="color: red">{{ error.tel.0 }}</p>

        </ul>
        <div class="moren">
            <label class="am-checkbox am-warning">
{#                <input type="checkbox"  checked="checked" value="" data-am-ucheck>设为默认#}
                <input type="checkbox" id="default" name='isdefault' checked="checked" value="1" data-am-ucheck>设为默认
            </label>

        </div>
        <input type="submit" class="login-btn" value="确认提交">
    </form>
    {% block foot_js %}
        <script type="text/javascript">
            $("#city").click(function (e) {
                SelCity(this, e);
                console.log(this);
            });
            $(function () {
                $("#default").on('click',function () {
                    if($(this).prop("check")==true){
                        $(this).val("1")
                    }else{
                        $(this).val("0")
                    }
                })
            })
        </script>
    {% endblock %}

{% endblock %}

market/templates/order/tureorder.html
{% extends 'public/base.html' %}
{% load static %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">确认订单</a>
            </h1>
	    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
     <div class="add-address">
           <a href="address.html">+新建收货地址</a>
           <i class="am-icon-angle-right"></i>
        </div>
        <div style="background: #eee; height: 10px;"></div>
        <ul class="shopcart-list" style="padding-bottom: 0;">
	    	<li>
                <img src="{% static 'images/test3.png' %}" class="shop-pic" />
                <div class="order-mid">
                	<div class="tit">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</div>
                	<div class="order-price">￥169 <i>X2</i></div>
                </div>
	    	</li>
	    	<li>
                <img src="{% static 'images/test3.png' %}" class="shop-pic" />
                <div class="order-mid">
                	<div class="tit">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</div>
                	<div class="order-price">￥169 <i>X2</i></div>
                </div>
	    	</li>
	    </ul>
	    <ul class="order-infor">
	    	<li class="order-infor-first">
	    		<span>商品总计：</span>
	    		<i>￥88.00</i>
	    	</li>
	    	<li class="order-infor-first">
	    		<span>运费：</span>
	    		<i>包邮</i>
	    	</li>
	    	<li class="order-infor-first">
	    		<a href="">积分抵费></a>
	    	</li>
	    	<li class="order-infor-first">
	    		<a href="">选择优惠券></a>
	    	</li>
	    </ul>
	    <div style="background: #eee; height: 10px;"></div>
	    <textarea placeholder="备注说明" class="bz-infor"></textarea>
	    <div style="background: #eee; height: 10px;"></div>
	    <div style="height: 55px;"></div>
	    <div class="shop-fix">
	    	<div class="order-text">
	    		应付总额：<span>￥188</span>
	    	</div>
	    	<a href="order.html" class="js-btn">提交订单</a>
	    </div>
{% endblock %}

{% block foot %}
    <!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="{% url 'goods:index' %}" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="{% url 'cart:shopcart' %}" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="{% url 'person:allorder' %}" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="{% url 'person:member' %}" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>


{% endblock %}